### ISSUE TITLE
不兼容高版本 node

### ISSUE THREAD

**Issue by heibaige123** [fex-team/fis-kernel#24]
```
[2023-07-17 20:12:49] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[2023-07-17 20:12:49]     at Object.writeFileSync (node:fs:2239:5)
[2023-07-17 20:12:49]     at _.write (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/fis-kernel/lib/util.js:466:12)
[2023-07-17 20:12:49]     at F.save (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/fis-kernel/lib/cache.js:31:18)
[2023-07-17 20:12:49]     at Command.<anonymous> (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/fis-command-release/release.js:279:27)
[2023-07-17 20:12:49]     at Command.<anonymous> (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/commander/index.js:256:8)
[2023-07-17 20:12:49]     at Command.emit (node:events:513:28)
[2023-07-17 20:12:49]     at Command.parseArgs (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/commander/index.js:479:12)
[2023-07-17 20:12:49]     at Command.parse (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/commander/index.js:377:21)
[2023-07-17 20:12:49]     at fis.cli.run (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/fis/fis.js:136:19)
[2023-07-17 20:12:49]     at Object.<anonymous> (/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/hpbfe/usrprofile/node_modules/fis/bin/fis:3:26) {
[2023-07-17 20:12:49]   code: 'ERR_INVALID_ARG_TYPE'
[2023-07-17 20:12:49] }
```

**Comment by 18boys** [comment]
已收到,稍候会处理best wish~
